function formatEgosRun(run) {
  if (!run) return undefined;

  return {
    runId: run.id,
    version: run.summary?.version || 'egos-1.0',
    generatedAt: (run.completedAt || run.startedAt).toISOString(),
    metrics: run.metrics || {},
    insights: Array.isArray(run.summary?.insights) ? run.summary.insights : [],
    coverage: (run.coverage || []).map((item) => ({
      id: item.id,
      axis: item.axis,
      provider: item.provider,
      status: item.status,
      message: item.message,
      resultCount: item.resultCount,
      consultedAt: item.consultedAt?.toISOString(),
      validUntil: item.validUntil?.toISOString(),
    })),
    entities: (run.entities || []).map((membership) => ({
      id: membership.entity.id,
      key: membership.entity.canonicalKey,
      type: membership.entity.entityType,
      name: membership.entity.name,
      normalizedName: membership.entity.normalizedName,
      properties: membership.entity.properties,
      depth: membership.depth,
      role: membership.role,
      confidence: membership.confidence,
      identifiers: membership.entity.identifiers || [],
      aliases: membership.entity.aliases || [],
    })),
    relationships: (run.relationships || []).map((membership) => ({
      id: membership.relationship.id,
      key: membership.relationship.canonicalKey,
      sourceEntityId: membership.relationship.sourceEntityId,
      targetEntityId: membership.relationship.targetEntityId,
      sourceName: membership.relationship.sourceEntity?.name,
      targetName: membership.relationship.targetEntity?.name,
      type: membership.relationship.relationshipType,
      label: membership.relationship.label,
      status: membership.status,
      confidence: membership.confidence,
      properties: membership.relationship.properties,
    })),
    evidences: (run.evidences || []).map((item) => ({
      id: item.id,
      entityId: item.entityId,
      relationshipId: item.relationshipId,
      provider: item.provider,
      sourceName: item.sourceName,
      sourceUrl: item.sourceUrl,
      query: item.query,
      identifier: item.identifier,
      excerpt: item.excerpt,
      confidence: item.confidence,
      retrievedAt: item.retrievedAt.toISOString(),
    })),
    findings: (run.findings || []).map((item) => ({
      id: item.id,
      entityId: item.entityId,
      relationshipId: item.relationshipId,
      axis: item.axis,
      status: item.status,
      severity: item.severity,
      title: item.title,
      explanation: item.explanation,
      confidence: item.confidence,
      reviewStatus: item.reviewStatus,
    })),
    resolutions: (run.resolutions || []).map((item) => ({
      id: item.id,
      sourceEntityId: item.sourceEntityId,
      sourceName: item.sourceEntity?.name,
      candidateEntityId: item.candidateEntityId,
      candidateName: item.candidateEntity?.name,
      score: item.score,
      status: item.status,
      signals: item.signals,
      reviewStatus: item.reviewStatus,
    })),
  };
}

module.exports = { formatEgosRun };
